"ExcelToJson.exe" ^
Localization.xlsx mst_develop_localize_Data/StreamingAssets/Localization.json ^
LocalizationAbility.xlsx mst_develop_localize_Data/StreamingAssets/LocalizationAbility.json ^
LocalizationArticle.xlsx mst_develop_localize_Data/StreamingAssets/LocalizationArticle.json ^
LocalizationBattle.xlsx mst_develop_localize_Data/StreamingAssets/LocalizationBattle.json ^
LocalizationJob.xlsx mst_develop_localize_Data/StreamingAssets/LocalizationJob.json ^
LocalizationCharacter.xlsx mst_develop_localize_Data/StreamingAssets/LocalizationCharacter.json ^
LocalizationUnit.xlsx mst_develop_localize_Data/StreamingAssets/LocalizationUnit.json ^
LocalizationElement.xlsx mst_develop_localize_Data/StreamingAssets/LocalizationElement.json ^
LocalizationScript.xlsx mst_develop_localize_Data/StreamingAssets/LocalizationScript.json ^
LocalizationCredit.xlsx mst_develop_localize_Data/StreamingAssets/LocalizationCredit.json
